openapi: 3.0.1
info:
  title: 名称
  description: 专注于文档解读与分析，支持多种文档格式，帮助用户理解文献内容，可以进行个性化配置，并以多种方式进行展示。
  version: "v1"
servers:
  - url: http://127.0.0.1:8081 # 替换成你实际服务启动的地址和端口，调试环境可以是localhost，正式上线需要换成公网IP
paths:
  /upload_file:
    post:
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                      - error
                  message:
                    type: string
                  data:
                    type: object
      x-return-raw:
        description: Returns the raw data.
        mediaType: application/json
        type: object
        name: RawData
#孟洋 4.13修改增加了image/png响应
  /generate_visualization:
    post:
      operationId: generateVisualization
      summary: 提取大纲生成树状图或思维导图
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateVisualizationRequest"
      responses:
        '200':
          description: 生成成功
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TreeResponse"
                  - $ref: "#/components/schemas/MindmapResponse"
            image/png:
              schema:
                type: string
                format: binary

  /extract_keywords:
    post:
      operationId: extractKeywords
      summary: 提取文件关键词
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExtractKeywordsRequest"
      responses:
        "200":
          description: 关键词提取成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeywordsResponse"

  /extract_examples:
    post:
      operationId: extractExamples
      summary: 提取文件实例
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExtractExamplesRequest"
      responses:
        "200":
          description: 实例提取成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExampleResponse"

  /extract_summary:
    post:
      operationId: extractSummary
      summary: 提取文件摘要
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExtractSummaryRequest"
      responses:
        "200":
          description: 摘要提取成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SummaryResponse"

  /answer_question:
    post:
      operationId: answerQuestion
      summary: 回答用户问题
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnswerQuestionRequest"
      responses:
        "200":
          description: 问题解答成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnswerResponse"

  /search_and_answer:
    post:
      operationId: searchAndAnswer
      summary: 在文件中搜索并回答问题
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchAndAnswerRequest"
      responses:
        "200":
          description: 问题解答成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"

components:

  schemas:
    UploadFileRequest:
      type: object
      properties:
        file:
          type: string
          format: binary

    GenerateVisualizationRequest:
      type: object
      properties:
        outline:
          $ref: "#/components/schemas/OutlineSection"

    OutlineSection:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        subsections:
          type: array
          items:
            $ref: "#/components/schemas/OutlineSection"

    TreeResponse:
      type: object
      properties:
        tree:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/TreeNode"

    TreeNode:
      type: object
      properties:
        title:
          type: string
        children:
          type: array
          items:
            $ref: "#/components/schemas/TreeNode"

    MindmapResponse:
      type: object
      properties:
        mindmap:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/MindmapNode"

    MindmapNode:
      type: object
      properties:
        text:
          type: string
        children:
          type: array
          items:
            $ref: "#/components/schemas/MindmapNode"

    ExtractKeywordsRequest:
      type: object
      properties:
        text:
          type: string

    KeywordsResponse:
      type: object
      properties:
        keywords:
          type: array
          items:
            type: string

    ExtractExamplesRequest:
      type: object
      properties:
        text:
          type: string

    ExampleResponse:
      type: object
      properties:
        examples:
          type: array
          items:
            type: string

    ExtractSummaryRequest:
      type: object
      properties:
        text:
          type: string

    SummaryResponse:
      type: object
      properties:
        summary:
          type: string

    AnswerQuestionRequest:
      type: object
      properties:
        question:
          type: string
        context:
          type: string

    AnswerResponse:
      type: object
      properties:
        answer:
          type: string

    SearchAndAnswerRequest:
      type: object
      properties:
        question:
          type: string
        file:
          type: string
        files:
          type: array
          items:
            type: string

    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/SearchResult"

    SearchResult:
      type: object
      properties:
        file:
          type: string
        answer:
          type: string

    SuccessResponse:
      type: object
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string